language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - bash run_tests.sh
  - bash run_lints.sh

notifications:
  email:
    on_success: always
    on_failure: always
